# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("/*\n"
"Material Dark Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Inspired on https://github.com/jxfwinter/qt-material-stylesheet\n"
"Company: GTRONICK\n"
"Last updated: 04/12/2018, 15:00.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/MaterialDark.qss\n"
"*/\n"
"\n"
"QMainWindow {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QColorDialog {\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTextEdit {\n"
"    background-color:#1e1d23;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPlainTextEdit {\n"
"    selection-background-color:#007b50;\n"
"    background-color:#1e1d23;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: inset;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-width: 1px;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-bottom: 2px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #37efba;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #37efba;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #808086;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding-bottom: 1px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: #a9b7c6;\n"
"    background:#1e1d23;\n"
"    selection-background-color:#007b50;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"QLabel {\n"
"    color: #a9b7c6;\n"
"}\n"
"QLCDNumber {\n"
"    color: #37e6b4;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:#1e1d23;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #04b97f;\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #a9b7c6;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"      background: #1e1d23;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background:#1e1d23;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: #04b97f;\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #FFFFFF;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #a9b7c6;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QMenu{\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:#1e1d23;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: #808086;\n"
"    padding: 3px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: #04b97f;\n"
"    border-bottom-width: 2px;\n"
"    border-style: solid;\n"
"    color: #FFFFFF;\n"
"    padding-left: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-left:3px;\n"
"    background-color: #1e1d23;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #a9b7c6;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:#1e1d23;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QRadioButton {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: #04b97f;\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #04b97f;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QDateEdit {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QComboBox {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QComboBox:editable {\n"
"    background: #1e1d23;\n"
"    color: #a9b7c6;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"    selection-color: #FFFFFF;\n"
"    selection-background-color: #1e1d23;\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color: #a9b7c6;    \n"
"    background: #1e1d23;\n"
"}\n"
"QFontComboBox {\n"
"    color: #a9b7c6;    \n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color: #1e1d23;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 14px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:1, y1:1, x2:0, y2:0, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 14px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: white;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #04b97f;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: #04b97f;\n"
"}\n"
"\n"
"/* 垂直滚动条整体区域 */\n"
"QScrollBar:vertical {\n"
"    background: #1e1d23;\n"
"    width: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"/* 垂直滚动条滑块 */\n"
"QScrollBar::handle:vertical {\n"
"    background: #3a3a3a; /* 深灰色滑块 */\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"/* 鼠标悬停在滑块上时变为主题翠绿色 */\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #04b97f;\n"
"}\n"
"\n"
"/* 隐藏垂直滚动条顶部的箭头按钮 */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* 水平滚动条整体区域 */\n"
"QScrollBar:horizontal {\n"
"    background: #1e1d23;\n"
"    height: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"/* 水平滚动条滑块 */\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3a3a3a;\n"
"    min-width: 20px;\n"
"    border-radius: 6px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"/* 鼠标悬停在滑块上 */\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #04b97f;\n"
"}\n"
"\n"
"/* 隐藏水平滚动条两端的箭头按钮 */\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"/* 滚动条背景（槽） */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QListView {\n"
"    selection-background-color:#007b50;\n"
"    background-color:#1e1d23;\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-width: 1px;\n"
"    color: #FFFFFF;\n"
"    font: 10pt \"JetBrains Mono\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setStyleSheet("")
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 18))
        self.menubar.setObjectName("menubar")
        self.menua = QtWidgets.QMenu(self.menubar)
        self.menua.setObjectName("menua")
        self.menub = QtWidgets.QMenu(self.menubar)
        self.menub.setObjectName("menub")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_load = QtWidgets.QAction(MainWindow)
        self.action_load.setObjectName("action_load")
        self.action_reload = QtWidgets.QAction(MainWindow)
        self.action_reload.setObjectName("action_reload")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_save_as = QtWidgets.QAction(MainWindow)
        self.action_save_as.setObjectName("action_save_as")
        self.action_cut = QtWidgets.QAction(MainWindow)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QtWidgets.QAction(MainWindow)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MainWindow)
        self.action_paste.setObjectName("action_paste")
        self.action_undo = QtWidgets.QAction(MainWindow)
        self.action_undo.setObjectName("action_undo")
        self.action_auto = QtWidgets.QAction(MainWindow)
        self.action_auto.setObjectName("action_auto")
        self.action_oneline = QtWidgets.QAction(MainWindow)
        self.action_oneline.setObjectName("action_oneline")
        self.action_sa = QtWidgets.QAction(MainWindow)
        self.action_sa.setObjectName("action_sa")
        self.action_sp = QtWidgets.QAction(MainWindow)
        self.action_sp.setObjectName("action_sp")
        self.action_cd = QtWidgets.QAction(MainWindow)
        self.action_cd.setObjectName("action_cd")
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_0 = QtWidgets.QAction(MainWindow)
        self.action_0.setObjectName("action_0")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_50 = QtWidgets.QAction(MainWindow)
        self.action_50.setObjectName("action_50")
        self.action_75 = QtWidgets.QAction(MainWindow)
        self.action_75.setObjectName("action_75")
        self.action_25 = QtWidgets.QAction(MainWindow)
        self.action_25.setObjectName("action_25")
        self.action_c50 = QtWidgets.QAction(MainWindow)
        self.action_c50.setObjectName("action_c50")
        self.action_c25 = QtWidgets.QAction(MainWindow)
        self.action_c25.setObjectName("action_c25")
        self.action_tab = QtWidgets.QAction(MainWindow)
        self.action_tab.setObjectName("action_tab")
        self.action_back = QtWidgets.QAction(MainWindow)
        self.action_back.setObjectName("action_back")
        self.action_33 = QtWidgets.QAction(MainWindow)
        self.action_33.setObjectName("action_33")
        self.action_c33 = QtWidgets.QAction(MainWindow)
        self.action_c33.setObjectName("action_c33")
        self.action_top = QtWidgets.QAction(MainWindow)
        self.action_top.setCheckable(True)
        self.action_top.setVisible(True)
        self.action_top.setObjectName("action_top")
        self.action800x600 = QtWidgets.QAction(MainWindow)
        self.action800x600.setObjectName("action800x600")
        self.action_steam_cmd = QtWidgets.QAction(MainWindow)
        self.action_steam_cmd.setObjectName("action_steam_cmd")
        self.action_gi = QtWidgets.QAction(MainWindow)
        self.action_gi.setObjectName("action_gi")
        self.action_gi_reset = QtWidgets.QAction(MainWindow)
        self.action_gi_reset.setObjectName("action_gi_reset")
        self.action_xp = QtWidgets.QAction(MainWindow)
        self.action_xp.setObjectName("action_xp")
        self.action_item_time = QtWidgets.QAction(MainWindow)
        self.action_item_time.setObjectName("action_item_time")
        self.action_item = QtWidgets.QAction(MainWindow)
        self.action_item.setObjectName("action_item")
        self.action_vpk = QtWidgets.QAction(MainWindow)
        self.action_vpk.setObjectName("action_vpk")
        self.action_bot_cmd = QtWidgets.QAction(MainWindow)
        self.action_bot_cmd.setObjectName("action_bot_cmd")
        self.action_bot_dir = QtWidgets.QAction(MainWindow)
        self.action_bot_dir.setObjectName("action_bot_dir")
        self.action_dota_dir = QtWidgets.QAction(MainWindow)
        self.action_dota_dir.setObjectName("action_dota_dir")
        self.action_general_lua = QtWidgets.QAction(MainWindow)
        self.action_general_lua.setObjectName("action_general_lua")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_killed_lua = QtWidgets.QAction(MainWindow)
        self.action_killed_lua.setObjectName("action_killed_lua")
        self.action33 = QtWidgets.QAction(MainWindow)
        self.action33.setObjectName("action33")
        self.action_100 = QtWidgets.QAction(MainWindow)
        self.action_100.setObjectName("action_100")
        self.action_c75 = QtWidgets.QAction(MainWindow)
        self.action_c75.setObjectName("action_c75")
        self.action_mod_dir = QtWidgets.QAction(MainWindow)
        self.action_mod_dir.setObjectName("action_mod_dir")
        self.action_skin_dir = QtWidgets.QAction(MainWindow)
        self.action_skin_dir.setObjectName("action_skin_dir")
        self.action_skin_dir2 = QtWidgets.QAction(MainWindow)
        self.action_skin_dir2.setObjectName("action_skin_dir2")
        self.action_clean_skin = QtWidgets.QAction(MainWindow)
        self.action_clean_skin.setObjectName("action_clean_skin")
        self.action_path_dir = QtWidgets.QAction(MainWindow)
        self.action_path_dir.setObjectName("action_path_dir")
        self.action_hero_dir = QtWidgets.QAction(MainWindow)
        self.action_hero_dir.setObjectName("action_hero_dir")
        self.action_gi_open = QtWidgets.QAction(MainWindow)
        self.action_gi_open.setObjectName("action_gi_open")
        self.action_c1 = QtWidgets.QAction(MainWindow)
        self.action_c1.setObjectName("action_c1")
        self.action_a1 = QtWidgets.QAction(MainWindow)
        self.action_a1.setObjectName("action_a1")
        self.action_ch = QtWidgets.QAction(MainWindow)
        self.action_ch.setObjectName("action_ch")
        self.menua.addAction(self.action_load)
        self.menua.addAction(self.action_reload)
        self.menua.addAction(self.action_save)
        self.menua.addAction(self.action_save_as)
        self.menua.addAction(self.action_open)
        self.menub.addAction(self.action_cut)
        self.menub.addAction(self.action_copy)
        self.menub.addAction(self.action_paste)
        self.menub.addAction(self.action_undo)
        self.menub.addAction(self.action_tab)
        self.menub.addAction(self.action_back)
        self.menu.addAction(self.action_auto)
        self.menu.addAction(self.action_oneline)
        self.menu.addAction(self.action_cd)
        self.menu.addAction(self.action_sa)
        self.menu.addAction(self.action_sp)
        self.menu.addAction(self.action_ch)
        self.menu_2.addAction(self.action_1)
        self.menu_2.addAction(self.action_0)
        self.menu_2.addAction(self.action_a1)
        self.menu_2.addAction(self.action_25)
        self.menu_2.addAction(self.action_33)
        self.menu_2.addAction(self.action_50)
        self.menu_2.addAction(self.action_75)
        self.menu_2.addAction(self.action_100)
        self.menu_2.addAction(self.action_c1)
        self.menu_2.addAction(self.action_c25)
        self.menu_2.addAction(self.action_c33)
        self.menu_2.addAction(self.action_c50)
        self.menu_2.addAction(self.action_c75)
        self.menu_3.addAction(self.action_top)
        self.menu_4.addAction(self.action_vpk)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_bot_cmd)
        self.menu_4.addAction(self.action_steam_cmd)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_gi_open)
        self.menu_4.addAction(self.action_gi)
        self.menu_4.addAction(self.action_gi_reset)
        self.menu_4.addAction(self.action_clean_skin)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_xp)
        self.menu_4.addAction(self.action_item_time)
        self.menu_4.addAction(self.action_item)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_path_dir)
        self.menu_4.addAction(self.action_hero_dir)
        self.menu_4.addAction(self.action_bot_dir)
        self.menu_4.addAction(self.action_dota_dir)
        self.menu_4.addAction(self.action_mod_dir)
        self.menu_4.addAction(self.action_skin_dir)
        self.menu_4.addAction(self.action_skin_dir2)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.action_general_lua)
        self.menu_4.addAction(self.action_killed_lua)
        self.menubar.addAction(self.menua.menuAction())
        self.menubar.addAction(self.menub.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menua.setTitle(_translate("MainWindow", "文件"))
        self.menub.setTitle(_translate("MainWindow", "编辑"))
        self.menu.setTitle(_translate("MainWindow", "操作"))
        self.menu_2.setTitle(_translate("MainWindow", "预设"))
        self.menu_3.setTitle(_translate("MainWindow", "窗口"))
        self.menu_4.setTitle(_translate("MainWindow", "脚本"))
        self.action_load.setText(_translate("MainWindow", "载入"))
        self.action_load.setShortcut(_translate("MainWindow", "L"))
        self.action_reload.setText(_translate("MainWindow", "重载"))
        self.action_reload.setShortcut(_translate("MainWindow", "R"))
        self.action_save.setText(_translate("MainWindow", "保存"))
        self.action_save.setShortcut(_translate("MainWindow", "S"))
        self.action_save_as.setText(_translate("MainWindow", "另存"))
        self.action_save_as.setShortcut(_translate("MainWindow", "A"))
        self.action_cut.setText(_translate("MainWindow", "剪切"))
        self.action_cut.setShortcut(_translate("MainWindow", "X"))
        self.action_copy.setText(_translate("MainWindow", "复制"))
        self.action_copy.setShortcut(_translate("MainWindow", "C"))
        self.action_paste.setText(_translate("MainWindow", "粘贴"))
        self.action_paste.setShortcut(_translate("MainWindow", "V"))
        self.action_undo.setText(_translate("MainWindow", "撤回"))
        self.action_undo.setShortcut(_translate("MainWindow", "Z"))
        self.action_auto.setText(_translate("MainWindow", "自动"))
        self.action_auto.setShortcut(_translate("MainWindow", "Space"))
        self.action_oneline.setText(_translate("MainWindow", "单行"))
        self.action_oneline.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.action_sa.setText(_translate("MainWindow", "魔晶"))
        self.action_sa.setShortcut(_translate("MainWindow", "Shift+A"))
        self.action_sp.setText(_translate("MainWindow", "魔杖"))
        self.action_sp.setShortcut(_translate("MainWindow", "Shift+S"))
        self.action_cd.setText(_translate("MainWindow", "冷却"))
        self.action_cd.setShortcut(_translate("MainWindow", "D"))
        self.action_1.setText(_translate("MainWindow", "=1"))
        self.action_1.setShortcut(_translate("MainWindow", "1"))
        self.action_0.setText(_translate("MainWindow", "=0"))
        self.action_0.setShortcut(_translate("MainWindow", "0"))
        self.action_15.setText(_translate("MainWindow", "+1"))
        self.action_15.setShortcut(_translate("MainWindow", "1"))
        self.action_50.setText(_translate("MainWindow", "+50%"))
        self.action_50.setShortcut(_translate("MainWindow", "5"))
        self.action_75.setText(_translate("MainWindow", "+75%"))
        self.action_75.setShortcut(_translate("MainWindow", "7"))
        self.action_25.setText(_translate("MainWindow", "+25%"))
        self.action_25.setShortcut(_translate("MainWindow", "2"))
        self.action_c50.setText(_translate("MainWindow", "-50%"))
        self.action_c50.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.action_c25.setText(_translate("MainWindow", "-25%"))
        self.action_c25.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_tab.setText(_translate("MainWindow", "缩进"))
        self.action_back.setText(_translate("MainWindow", "退格"))
        self.action_back.setShortcut(_translate("MainWindow", "Backspace"))
        self.action_33.setText(_translate("MainWindow", "+33%"))
        self.action_33.setShortcut(_translate("MainWindow", "3"))
        self.action_c33.setText(_translate("MainWindow", "-33%"))
        self.action_c33.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.action_top.setText(_translate("MainWindow", "置顶"))
        self.action_top.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.action800x600.setText(_translate("MainWindow", "1000x800"))
        self.action_steam_cmd.setText(_translate("MainWindow", "复制steam启动项"))
        self.action_gi.setText(_translate("MainWindow", "更新gi"))
        self.action_gi_reset.setText(_translate("MainWindow", "重置gi"))
        self.action_xp.setText(_translate("MainWindow", "更新经验和金钱"))
        self.action_item_time.setText(_translate("MainWindow", "更新中立物品时间"))
        self.action_item.setText(_translate("MainWindow", "更新物品属性"))
        self.action_vpk.setText(_translate("MainWindow", "生成vpk文件"))
        self.action_vpk.setShortcut(_translate("MainWindow", "Ctrl+Return"))
        self.action_bot_cmd.setText(_translate("MainWindow", "复制bot指令"))
        self.action_bot_dir.setText(_translate("MainWindow", "打开bot文件夹"))
        self.action_dota_dir.setText(_translate("MainWindow", "打开dota文件夹"))
        self.action_general_lua.setText(_translate("MainWindow", "打开general.lua"))
        self.action_open.setText(_translate("MainWindow", "打开"))
        self.action_open.setShortcut(_translate("MainWindow", "O"))
        self.action_killed_lua.setText(_translate("MainWindow", "打开OnEntityKilled.lua"))
        self.action33.setText(_translate("MainWindow", "1"))
        self.action_100.setText(_translate("MainWindow", "+100%"))
        self.action_c75.setText(_translate("MainWindow", "-75%"))
        self.action_c75.setShortcut(_translate("MainWindow", "Ctrl+7"))
        self.action_mod_dir.setText(_translate("MainWindow", "打开mod文件夹"))
        self.action_skin_dir.setText(_translate("MainWindow", "打开Dota2SkinChanger"))
        self.action_skin_dir2.setText(_translate("MainWindow", "打开Dota2SkinChanger2"))
        self.action_clean_skin.setText(_translate("MainWindow", "清空皮肤"))
        self.action_path_dir.setText(_translate("MainWindow", "打开根目录"))
        self.action_hero_dir.setText(_translate("MainWindow", "打开英雄文件夹"))
        self.action_gi_open.setText(_translate("MainWindow", "打开gi"))
        self.action_c1.setText(_translate("MainWindow", "-1"))
        self.action_c1.setShortcut(_translate("MainWindow", "-"))
        self.action_a1.setText(_translate("MainWindow", "+1"))
        self.action_a1.setShortcut(_translate("MainWindow", "+"))
        self.action_ch.setText(_translate("MainWindow", "充能"))
        self.action_ch.setShortcut(_translate("MainWindow", "H"))
